

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ WEB (already correct)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbrUX80wA2AuCCuEiEpjqdORO1yKCh7uE',
    appId: '1:23552307806:web:d39eaf5e8744fad69a7acf',
    messagingSenderId: '23552307806',
    projectId: 'myflutterapp-e424a',
    authDomain: 'myflutterapp-e424a.firebaseapp.com',
    storageBucket: 'myflutterapp-e424a.firebasestorage.app',
    measurementId: 'G-3KT5D5G93Y',
    databaseURL:
        "https://myflutterapp-e424a-default-rtdb.asia-southeast1.firebasedatabase.app/", // ✅ OK
  );

  // ✅ ANDROID (FIX ADDED)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTuI3ZgKgnlokEfq7HJWoQTy4sUYUsKsI',
    appId: '1:23552307806:android:b2997a131de3132e9a7acf',
    messagingSenderId: '23552307806',
    projectId: 'myflutterapp-e424a',
    storageBucket: 'myflutterapp-e424a.firebasestorage.app',
    databaseURL:
        "https://myflutterapp-e424a-default-rtdb.asia-southeast1.firebasedatabase.app/", // ✅ ADDED
  );

  // ✅ IOS (OPTIONAL BUT SAFE)
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxecOKsqXcGbHV-kSOmVWncv1uHm3TOaM',
    appId: '1:23552307806:ios:5a78c080869d75fe9a7acf',
    messagingSenderId: '23552307806',
    projectId: 'myflutterapp-e424a',
    storageBucket: 'myflutterapp-e424a.firebasestorage.app',
    iosClientId:
        '23552307806-ub748u4tfr8njihcpn9do0r31ngka1kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
    databaseURL:
        "https://myflutterapp-e424a-default-rtdb.asia-southeast1.firebasedatabase.app/", // ✅ ADDED
  );

  // ✅ MACOS (OPTIONAL BUT SAFE)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxecOKsqXcGbHV-kSOmVWncv1uHm3TOaM',
    appId: '1:23552307806:ios:5a78c080869d75fe9a7acf',
    messagingSenderId: '23552307806',
    projectId: 'myflutterapp-e424a',
    storageBucket: 'myflutterapp-e424a.firebasestorage.app',
    iosClientId:
        '23552307806-ub748u4tfr8njihcpn9do0r31ngka1kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecom',
    databaseURL:
        "https://myflutterapp-e424a-default-rtdb.asia-southeast1.firebasedatabase.app/", // ✅ ADDED
  );

  // ✅ WINDOWS (FIX ADDED)
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbrUX80wA2AuCCuEiEpjqdORO1yKCh7uE',
    appId: '1:23552307806:web:ab16ef22659ff4039a7acf',
    messagingSenderId: '23552307806',
    projectId: 'myflutterapp-e424a',
    authDomain: 'myflutterapp-e424a.firebaseapp.com',
    storageBucket: 'myflutterapp-e424a.firebasestorage.app',
    measurementId: 'G-BDX3FZ0M86',
    databaseURL:
        "https://myflutterapp-e424a-default-rtdb.asia-southeast1.firebasedatabase.app/", // ✅ ADDED
  );
}